name: Cloud RDP Maker

on:
  workflow_dispatch: # Website theke manual trigger korar jonno

jobs:
  build-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Maximum 6 hours limit
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Desktop and VNC
        run: |
          sudo apt update
          sudo apt install -y tigervnc-standalone-server xfce4 xfce4-goodies
          mkdir -p ~/.vnc
          echo "12345678" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo -e "#!/bin/bash\nstartxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver :1 -geometry 1280x720 -depth 24

      - name: Start Pinggy TCP Tunnel
        run: |
          echo "=========================================="
          echo "GENERATING TCP TUNNEL FOR RVNC VIEWER..."
          echo "=========================================="
          ssh -o StrictHostKeyChecking=no -p 443 -R 0:localhost:5901 tcp@a.pinggy.io
          
